---
title: "data_generation"
author: "Jack Thomas"
date: "5/9/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data generation for Blanc et al. model.

```{r define}
# number of sites
nsites <- 4**2

# number of individuals in capture history
n <- 10

# number of sampling occasions in capture-recapture
nsample_cap <- 5

# number of sampling occasions in presence-absence
nsample_pa <- 7

# capture probability
p <- 0.5

# occupancy probability
occupancy <- 0.3

# amount of movement for the species
tau <- 0.1

# number of camera traps
ntraps <- 3
```


# Simulate Individuals

```{r individuals}
set.seed(1313)
# our study area is the unit square

# define homerange centers

# Poisson process, with x, y coordinates as independent uniform
# random variables

homeranges <- array(data = NA, dim = c(n, 2), dimnames = list(c(1:n), c("x", "y")))

for (i in 1:n) {
  x <- runif(1)
  y <- runif(1)
  homeranges[i, 1] <- x
  homeranges[i, 2] <- y
}

# plotting homeranges for validation
par(pty = "s")
plot(homeranges, xlim = c(0, 1), ylim = c(0, 1))
```
# Capture-Recapture Data

```{r Capture-Recapture Traps}
set.seed(1235)
traps <- array(data = NA, dim = c(ntraps, 2), dimnames = list(c(1:ntraps), c("x", "y")))

# randomly place camera traps
for (i in 1:ntraps) {
  x <- runif(1)
  y <- runif(1)
  traps[i, 1] <- x
  traps[i, 2] <- y
}

# plot traps on study area with homeranges included
par(pty = "s", mar = c(5, 4, 4, 8), xpd = TRUE)

plot(homeranges, xlim = c(0, 1), ylim = c(0, 1))
points(traps, col = "red", pch = 15)
legend("topright", inset = c(-.5, 0), c("homerange", "camera trap"), cex = .8, col = c("black", "red"), pch = c(1, 15))
```



# Presence-Absence Data

```{r presence-absence area}
# We now have a m x m grid for the unit square as our divided area

# number of grid cells per row
m <- sqrt(nsites)

# x coordinates
regions_x <- array(data = NA, dim = c(m * m, 2))

for (k in 0:m - 1) {
  for (i in 1:m) {
    regions_x[i + k * m, 1] <- (i - 1) / m
    regions_x[i + k * m, 2] <- regions_x[i + k * m, 1] + 1 / m
  }
}

# y coordinates
regions_y <- array(data = NA, dim = c(m * m, 2))
j <- 0
for (i in 1:(m * m)) {
  regions_y[i, 1] <- j
  regions_y[i, 2] <- j + 1 / m

  if (i %% m == 0) {
    j <- j + 1 / m
  }
}

# regions are in x0,x1,y0,y1 form
regions <- cbind(regions_x, regions_y)

# plot grid cells on study area with homerange centers and individuals labeled
par(pty = "s")
plot(homeranges, xlim = c(0, 1), ylim = c(0, 1))
for (i in 0:m) {
  abline(v = i / m)
  abline(h = i / m)
}
# individuals labeled from 1 to n
text(homeranges, labels = rownames(homeranges), cex = 1.5, font = 2, pos = 3)
```

```{r pa-data}
library(OpenMx)
options(scipen = 999)

# simulate presence-absence data for each region for each period nsample_occ

# 2D matrix with rows being regions and columns being time periods
presence_absence <- array(data = 0, dim = c(m * m, nsample_pa))


#' Calculate Proportion of Time Spent in Grid Cell
#'
#' @param x The x coordinate of the homerange for an individual
#' @param y The y coordinate of the homerange for an individual
#' @param x0 The starting x value for the grid cell
#' @param x1 The ending x value for the grid cell
#' @param y0 The starting y value for the grid cell
#' @param y1 The ending y value for the grid cell
#' @param tau The movement parameter for the species, lower is less movement
#'
#' @return A value between 0 and 1 indicating the proportion of time that the
#'         individual spends in the given grid cell
#' @export
#'
#' @examples
#' # show high proportion when homerange in center of grid cell
#' calc_prop(0.25 / 2, 0.25 / 2, 0, 0.25, 0, 0.25, 0.1)
calc_prop <- function(x, y, x0, x1, y0, y1, tau) {
  covariance <- matrix(c(tau^2, 0, 0, tau^2), nrow = 2, ncol = 2)
  means <- c(x, y)
  lbound <- c(x0, y0)
  ubound <- c(x1, y1)

  prop <- omxMnor(covariance, means, lbound, ubound)[1]
  return(prop)
}


indi_props <- array(data = NA, dim = c(nrow(regions), nrow(homeranges)))
for (i in 1:nrow(regions)) {
  # compute proportion of time each individual spends in this region
  for (j in 1:nrow(homeranges)) {
    x <- homeranges[j, 1]
    y <- homeranges[j, 2]

    x0 <- regions[i, 1]
    x1 <- regions[i, 2]

    y0 <- regions[i, 3]
    y1 <- regions[i, 4]

    prop <- calc_prop(x, y, x0, x1, y0, y1, tau)
    indi_props[i, j] <- prop
  }

  # run simulation for presence-absence data
  # in this region
  for (j in 1:nrow(homeranges)) {
    for (k in 1:nsample_pa) {
      # assume detection probability is proportional to time spent in region
      detection_prob <- indi_props[i, j]
      rv <- runif(1)

      if (detection_prob >= rv) {
        presence_absence[i, k] <- 1
      }
    }
  }
}

# columns do not necessarily sum to 1, because individual may spend
# time outside the study area
# colSums(indi_props)
```


```{r plots}
library(gplots)

# create heatmap of study area, where the sum of detections for each region is plotted

detect_sums <- rowSums(presence_absence)


d_sums_mat <- apply(t(matrix(data = detect_sums, nrow = m, ncol = m)), 2, rev)

col_pallette <- colorRampPalette(c("grey", "yellow", "orange", "red"))

heatmap.2(d_sums_mat, Rowv = FALSE, Colv = FALSE, dendrogram = "none", col = col_pallette, tracecol = NA, labRow = NA, labCol = NA, margins = c(.1, .1))

# plot grid cells on study area with homerange centers and individuals labeled
par(pty = "s")
plot(homeranges, xlim = c(0, 1), ylim = c(0, 1))
for (i in 0:m) {
  abline(v = i / m)
  abline(h = i / m)
}
# individuals labeled from 1 to n
text(homeranges, labels = rownames(homeranges), cex = 1.5, font = 2, pos = 3)
```
